version: "3.8"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    networks:
      - flask-net
    volumes:
      - .:/app
    env_file:
      - .env

networks:
  flask-net:
    driver: bridge